[tool.poetry]
name = "radixtarget"
version = "0.0.9"
description = "Check whether an IP address belongs to a cloud provider"
authors = ["TheTechromancer"]
license = "GPL-3.0"
readme = "README.md"
repository = "https://github.com/blacklanternsecurity/radixtarget"
homepage = "https://github.com/blacklanternsecurity/radixtarget"

[tool.poetry.urls]
"PyPi" = "https://pypi.org/project/radixtarget/"

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.group.dev.dependencies]
black = ">=22.12,<25.0"
flake8 = ">=6.1,<8.0"
pytest = "^8.1.1"
pytest-cov = "^5.0.0"

[tool.poetry-dynamic-versioning]
enable = true
metadata = false
format-jinja = 'v1.0.0.{{ distance }}'

[build-system]
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning>=1.0.0,<2.0.0"]
build-backend = "poetry_dynamic_versioning.backend"
